version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./findings.json:/app/findings.json:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - TZ=Europe/Berlin
    restart: always
