version: '3'
services:
  scraper:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./config.json:/app/config.json
      - ./config.template.json:/app/config.template.json
      - ./findings.json:/app/findings.json
    environment:
      - TZ=Europe/Berlin
    restart: always
