version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./findings.json:/app/findings.json
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Berlin
    restart: always
