version: '3.8'

services:
  scraper:
    container_name: baycheck_scraper
    build: .
    volumes:
      - type: bind
        source: ./findings.json
        target: /app/findings.json
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: ./logs
        target: /app/logs
    environment:
      - TZ=Europe/Berlin
    restart: always
